### ISSUE TITLE
Please fix icon

### ISSUE THREAD

**Issue by stoecker** [species/josm-preset-traffic_sign_direction#2]
Hello,

the icon path misses a part. It should be "styles/standard/vehicle/restriction/right_of_way.png". Please fix it, as this causes permanent server warnings.

Also I'd set the link to this GitHub project as "link".

**Comment by species** [comment]
fixed with d95e8ec21c17ae2faef711a5207812fbaf4af90d, 5b70302b9a908e56e336cf39ffc17e3f4de42631.
